server:
  port: 8081
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/SimonSaezCorrea/MicroService-MilkStgo
          search-paths: config-data
  application:
    name: Config

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'