server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/SimonSaezCorrea/MicroService-MilkStgo
          search-paths: config-data
  application:
    name: Config
