apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-eureka-deployment
  labels:
    app: backend-eureka-deployment
spec:
  selector:
    matchLabels:
      app: backend-eureka-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: backend-eureka-deployment
    spec:
      containers:
        - name: backend-eureka
          image: simonsaez/minikube-microservice-milkstgo-eureka
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: backend-eureka-service
  labels:
    app: backend-eureka-service
spec:
  selector:
    app: backend-eureka-deployment
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: LoadBalancer