apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-acopioleche-deployment
  labels:
    app: backend-acopioleche-deployment
spec:
  selector:
    matchLabels:
      app: backend-acopioleche-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: backend-acopioleche-deployment
    spec:
      containers:
        - name: backend-acopioleche
          image: simonsaez/minikube-microservice-milkstgo-acopioleche
          ports:
            - containerPort: 8084
          env:
            - name: DATABASE-URL
              value: postgresql://postgres:Simon_789@localhost:5432/MilkStgo_MicroService_AcopioLeche
---
apiVersion: v1
kind: Service
metadata:
  name: backend-acopioleche-service
  labels:
    app: backend-acopioleche-service
spec:
  selector:
    app: backend-acopioleche-deployment
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer