apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-planilladepago-deployment
  labels:
    app: backend-planilladepago-deployment
spec:
  selector:
    matchLabels:
      app: backend-planilladepago-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: backend-planilladepago-deployment
    spec:
      containers:
        - name: backend-planilladepago
          image: simonsaez/minikube-microservice-milkstgo-planilladepago
          ports:
            - containerPort: 8082
          env:
            - name: DB-HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-db
                  key: HOST
            - name: DB-NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-db
                  key: POSTGRES_DB_PLANILLADEPAGO
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres_credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres_credentials
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: backend-planilladepago-service
  labels:
    app: backend-planilladepago-service
spec:
  selector:
    app: backend-planilladepago-deployment
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer