apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-grasaysolidostotales-deployment
  labels:
    app: backend-grasaysolidostotales-deployment
spec:
  selector:
    matchLabels:
      app: backend-grasaysolidostotales-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: backend-grasaysolidostotales-deployment
    spec:
      containers:
        - name: backend-grasaysolidostotales
          image: simonsaez/minikube-microservice-milkstgo-grasaysolidostotales
          ports:
            - containerPort: 8083
          env:
            - name: DATABASE-URL
              value: postgresql://postgres:Simon_789@localhost:5432/MilkStgo_MicroService_GrasaYSolidoTotales
---
apiVersion: v1
kind: Service
metadata:
  name: backend-grasaysolidostotales-service
  labels:
    app: backend-grasaysolidostotales-service
spec:
  selector:
    app: backend-grasaysolidostotales-deployment
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer