FROM openjdk:17
ARG JAR_FILE=target/MicroService-MilkStgo-GrasaYSolidosTotales.jar
COPY ${JAR_FILE} MicroService-MilkStgo-GrasaYSolidosTotales.jar
ENTRYPOINT ["java","-jar","/MicroService-MilkStgo-GrasaYSolidosTotales.jar"]