server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://backend-eureka-service:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: MicroService-MilkStgo-AcopioLeche
          uri: lb://MicroService-MilkStgo-AcopioLeche
          predicates:
            - Path=/acopio_leche/**
        - id: MicroService-MilkStgo-GrasaYSolidosTotales
          uri: lb://MicroService-MilkStgo-GrasaYSolidosTotales
          predicates:
            - Path=/grasa_solidos_totales/**
        - id: MicroService-MilkStgo-PlanillaPagoLeche
          uri: lb://MicroService-MilkStgo-PlanillaPagoLeche
          predicates:
            - Path=/pago_planilla/**
        - id: MicroService-MilkStgo-Proveedores
          uri: lb://MicroService-MilkStgo-Proveedores
          predicates:
            - Path=/proveedor/**