server:
  port: 8085
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: MicroService-MilkStgo-AcopioLeche
          uri: lb://MicroService-MilkStgo-AcopioLeche
          predicates:
            - Path=/acopio_leche/**
        - id: MicroService-MilkStgo-GrasaYSolidosTotales
          uri: lb://MicroService-MilkStgo-GrasaYSolidosTotales
          predicates:
            - Path=/grasa_solidos_totales/**
        - id: MicroService-MilkStgo-PlanillaPagoLeche
          uri: lb://MicroService-MilkStgo-PlanillaPagoLeche
          predicates:
            - Path=/pago_planilla/**
        - id: MicroService-MilkStgo-Proveedores
          uri: lb://MicroService-MilkStgo-Proveedores
          predicates:
            - Path=/proveedor/**