FROM openjdk:17
ARG JAR_FILE=target/MicroService-MilkStgo-PlanillaPagoLeche.jar
COPY ${JAR_FILE} MicroService-MilkStgo-PlanillaPagoLeche.jar
ENTRYPOINT ["java","-jar","/MicroService-MilkStgo-PlanillaPagoLeche.jar"]