apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-planilladepago-deployment
  labels:
    app: backend-planilladepago-deployment
spec:
  selector:
    matchLabels:
      app: backend-planilladepago-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-planilladepago-deployment
    spec:
      containers:
        - name: backend-planilladepago
          image: simonsaez/minikube-microservice-milkstgo-planilladepago
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://backend-config-service:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://backend-eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: POSTGRES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_HOST
            - name: POSTGRES_DB_PLANILLADEPAGO
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_PLANILLADEPAGO
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: backend-planilladepago-service
  labels:
    app: backend-planilladepago-service
spec:
  selector:
    app: backend-planilladepago-deployment
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer