apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  POSTGRES_DB_HOST: postgres
  #base de dato Acopio
  POSTGRES_DB_ACOPIOLECHE: milkstgo_microservice_acopioleche
  #base de dato Proveedor
  POSTGRES_DB_PROVEEDOR: milkstgo_microservice_proveedores
  #base de dato Grasa y Solidos Totales
  POSTGRES_DB_GRASAYSOLIDOSTOTALES: milkstgo_microservice_grasaysolidototales
  #base de dato Planilla de Pago
  POSTGRES_DB_PLANILLADEPAGO: milkstgo_microservice_planillapagoleche